version: '3.3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always

  python:
    build:
      context: .
      dockerfile: Dockerfile-python
    ports:
      - 8000:8000
    depends_on:
      - mysql
    restart: always

