name: Image Registry
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:        

env:
  DOCKER_IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/python-fastapi
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies and Pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov

      - name: Run unit tests
        run: pytest --cov=./test --cov-report=xml --doctest-modules

      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-python
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
        env:
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.GITHU_TOKEN }}
