name: Python CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set sonar properties
        run: |
          SONAR_PROJECT_KEY=${GITHUB_REPOSITORY/\//_}
          echo -e "sonar.projectKey=$SONAR_PROJECT_KEY \nsonar.organization=ovicorpsystems" > sonar-project.properties
          cat sonar-project.properties

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov

      - name: Run unit tests
        run: pytest --cov=./test --cov-report=xml --doctest-modules

      - name: SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t python-fastapi .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag python-fastapi ${{ secrets.DOCKER_REGISTRY }}/python-fastapi
          docker push ${{ secrets.DOCKER_REGISTRY }}/python-fastapi

      - name: Save Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: ${{ secrets.DOCKER_REGISTRY }}/python-fastapi
